FROM node:22-alpine AS base

# Install dependencies only when needed
FROM base AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install dependencies based on the preferred package manager.
# `--prefer-offline --no-audit --no-fund` shaves a few seconds off the
# network/registry chatter on cold builds.
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci --prefer-offline --no-audit --no-fund; \
  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
  else echo "Lockfile not found." && exit 1; \
  fi

# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry during the build.
# ENV NEXT_TELEMETRY_DISABLED 1

# Set environment variables for the build
# ARG NODE_ENV=production
# ENV NODE_ENV=${NODE_ENV}

ARG NEXT_PUBLIC_API_URL=NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

ARG NEXT_PUBLIC_API_URL_V3=NEXT_PUBLIC_API_URL_V3
ENV NEXT_PUBLIC_API_URL_V3=${NEXT_PUBLIC_API_URL_V3}

ARG NEXT_PUBLIC_GOOGLE_CLIENT_ID=NEXT_PUBLIC_GOOGLE_CLIENT_ID
ENV NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}

ARG NEXT_PUBLIC_MSAL_CLIENT_ID=NEXT_PUBLIC_MSAL_CLIENT_ID
ENV NEXT_PUBLIC_MSAL_CLIENT_ID=${NEXT_PUBLIC_MSAL_CLIENT_ID}

ARG NEXT_PUBLIC_MSAL_AUTHORITY=NEXT_PUBLIC_MSAL_AUTHORITY
ENV NEXT_PUBLIC_MSAL_AUTHORITY=${NEXT_PUBLIC_MSAL_AUTHORITY}

ARG NEXT_PUBLIC_MSAL_REDIRECT_URI=NEXT_PUBLIC_MSAL_REDIRECT_URI
ENV NEXT_PUBLIC_MSAL_REDIRECT_URI=${NEXT_PUBLIC_MSAL_REDIRECT_URI}

ARG NEXT_PUBLIC_AI_CHAT_URL=NEXT_PUBLIC_AI_CHAT_URL
ENV NEXT_PUBLIC_AI_CHAT_URL=${NEXT_PUBLIC_AI_CHAT_URL}

ARG NEXT_PUBLIC_AI_API=NEXT_PUBLIC_AI_API
ENV NEXT_PUBLIC_AI_API=${NEXT_PUBLIC_AI_API}

ARG NEXT_PUBLIC_SYNC_FUSION_LICENSE_KEY=NEXT_PUBLIC_SYNC_FUSION_LICENSE_KEY
ENV NEXT_PUBLIC_SYNC_FUSION_LICENSE_KEY=${NEXT_PUBLIC_SYNC_FUSION_LICENSE_KEY}

ARG NEXT_PUBLIC_FILES_UPLOAD_LIMIT=NEXT_PUBLIC_FILES_UPLOAD_LIMIT
ENV NEXT_PUBLIC_FILES_UPLOAD_LIMIT=${NEXT_PUBLIC_FILES_UPLOAD_LIMIT}

ARG NEXT_PUBLIC_SENTRY_DSN=NEXT_PUBLIC_SENTRY_DSN
ENV NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN}

ARG NEXT_PUBLIC_SENTRY_ORG=NEXT_PUBLIC_SENTRY_ORG
ENV NEXT_PUBLIC_SENTRY_ORG=${NEXT_PUBLIC_SENTRY_ORG}

ARG NEXT_PUBLIC_SENTRY_PROJECT=NEXT_PUBLIC_SENTRY_PROJECT
ENV NEXT_PUBLIC_SENTRY_PROJECT=${NEXT_PUBLIC_SENTRY_PROJECT}

ARG NEXT_PUBLIC_ENVIRONMENT=NEXT_PUBLIC_ENVIRONMENT
ENV NEXT_PUBLIC_ENVIRONMENT=${NEXT_PUBLIC_ENVIRONMENT}

ARG NEXT_PUBLIC_ANALYTICS_HOST=NEXT_PUBLIC_ANALYTICS_HOST
ENV NEXT_PUBLIC_ANALYTICS_HOST=${NEXT_PUBLIC_ANALYTICS_HOST}

ARG NEXT_PUBLIC_ANALYTICS_KEY=NEXT_PUBLIC_ANALYTICS_KEY
ENV NEXT_PUBLIC_ANALYTICS_KEY=${NEXT_PUBLIC_ANALYTICS_KEY}

ARG NEXT_PUBLIC_COOKIE_DOMAIN=NEXT_PUBLIC_COOKIE_DOMAIN
ENV NEXT_PUBLIC_COOKIE_DOMAIN=${NEXT_PUBLIC_COOKIE_DOMAIN}

ARG NEXT_PUBLIC_EVENTS_SOCKET_URL=NEXT_PUBLIC_EVENTS_SOCKET_URL
ENV NEXT_PUBLIC_EVENTS_SOCKET_URL=${NEXT_PUBLIC_EVENTS_SOCKET_URL}

ARG NEXT_PUBLIC_SUPABASE_ANON_SECRET_MAIN=NEXT_PUBLIC_SUPABASE_ANON_SECRET_MAIN
ENV NEXT_PUBLIC_SUPABASE_ANON_SECRET_MAIN=${NEXT_PUBLIC_SUPABASE_ANON_SECRET_MAIN}

ARG NEXT_PUBLIC_SUPABASE_SEARCH_ANON_KEY=NEXT_PUBLIC_SUPABASE_SEARCH_ANON_KEY
ENV NEXT_PUBLIC_SUPABASE_SEARCH_ANON_KEY=${NEXT_PUBLIC_SUPABASE_SEARCH_ANON_KEY}

ARG NEXT_PUBLIC_SUPABASE_URL_MAIN=NEXT_PUBLIC_SUPABASE_URL_MAIN
ENV NEXT_PUBLIC_SUPABASE_URL_MAIN=${NEXT_PUBLIC_SUPABASE_URL_MAIN}

ARG NEXT_PUBLIC_SUPABASE_URL_SEARCH=NEXT_PUBLIC_SUPABASE_URL_SEARCH
ENV NEXT_PUBLIC_SUPABASE_URL_SEARCH=${NEXT_PUBLIC_SUPABASE_URL_SEARCH}

# Support-contact email shown on auth dead-ends (unauthorized / SSO failures).
# Real default (matches the code fallback) so an unset value never renders blank.
ARG NEXT_PUBLIC_SUPPORT_EMAIL=support@head-hunter.example
ENV NEXT_PUBLIC_SUPPORT_EMAIL=${NEXT_PUBLIC_SUPPORT_EMAIL}

ARG NEXT_PUBLIC_AI_URL=NEXT_PUBLIC_AI_URL
ENV NEXT_PUBLIC_AI_URL=${NEXT_PUBLIC_AI_URL}

ARG NEXT_PUBLIC_COPILOT_API_URL=NEXT_PUBLIC_COPILOT_API_URL
ENV NEXT_PUBLIC_COPILOT_API_URL=${NEXT_PUBLIC_COPILOT_API_URL}

ARG NEXT_PUBLIC_NOTEBOOK_URL=NEXT_PUBLIC_NOTEBOOK_URL
ENV NEXT_PUBLIC_NOTEBOOK_URL=${NEXT_PUBLIC_NOTEBOOK_URL}

ARG NEXT_PUBLIC_FCM_VAPID_KEY=NEXT_PUBLIC_FCM_VAPID_KEY
ENV NEXT_PUBLIC_FCM_VAPID_KEY=${NEXT_PUBLIC_FCM_VAPID_KEY}

ARG NEXT_PUBLIC_FIREBASE_API_KEY=NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}

ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}

ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID=NEXT_PUBLIC_FIREBASE_PROJECT_ID
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}

ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}

ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}

ARG NEXT_PUBLIC_FIREBASE_APP_ID=NEXT_PUBLIC_FIREBASE_APP_ID
ENV NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}

ARG NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
ENV NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}

ARG NEXT_PUBLIC_DEEP_SEARCH_SUPABASE_URL=NEXT_PUBLIC_DEEP_SEARCH_SUPABASE_URL
ENV NEXT_PUBLIC_DEEP_SEARCH_SUPABASE_URL=${NEXT_PUBLIC_DEEP_SEARCH_SUPABASE_URL}

ARG NEXT_PUBLIC_DEEP_SEARCH_SUPABASE_PUBLIC_KEY=NEXT_PUBLIC_DEEP_SEARCH_SUPABASE_PUBLIC_KEY
ENV NEXT_PUBLIC_DEEP_SEARCH_SUPABASE_PUBLIC_KEY=${NEXT_PUBLIC_DEEP_SEARCH_SUPABASE_PUBLIC_KEY}

ARG NEXT_PUBLIC_AUTH_REFRESH_LEAD_MINUTES=50
ENV NEXT_PUBLIC_AUTH_REFRESH_LEAD_MINUTES=${NEXT_PUBLIC_AUTH_REFRESH_LEAD_MINUTES}

# Standard GitHub-hosted runners are 2 vCPU / 7.8 GiB (6.8 GiB available
# after OS/runner agent). Historic OOM at the 4 GB V8 default came from
# Sentry source-map widening + JSX annotation (both disabled in
# `sentryConfig.js`). 5120 MB caps V8's old space so peak RSS
# (~5.6 GiB incl. native heap + new space) leaves ~1.2 GiB margin
# before swap. Matches `ci.yml`. Re-tune if we move to a larger
# runner class.
ARG NODE_OPTIONS=--max-old-space-size=5120
ENV NODE_OPTIONS=${NODE_OPTIONS}

RUN npm run build

# If using npm comment out above and use below instead
# RUN npm run build

# Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

# Uncomment the following line in case you want to disable telemetry during runtime.
# ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# COPY --from=builder /app/public ./public

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Copy the public folder
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

USER nextjs

EXPOSE 3000

# Set environment variable for runtime
ENV PORT 3000

RUN printenv

CMD ["node", "server.js"]
