import type { LegalSection } from "@/components/landing/LegalPage";

export const PRIVACY_UPDATED = "September 7, 2026";

export const PRIVACY_INTRO: readonly string[] = [
  "Head-Hunters.com (“Head-Hunters”, “we”, “us”, or “our”) respects your privacy and is committed to protecting personal information collected through the Head-Hunters.com website, recruiting marketplace, applications, services, and related features (collectively, the “Platform”).",
  "This Privacy Policy explains what information we collect, how we use and disclose it, how we protect it, and the choices and rights that may be available to you.",
  "By accessing or using Head-Hunters.com, you acknowledge the practices described in this Privacy Policy.",
];

export const PRIVACY_SECTIONS: readonly LegalSection[] = [
  {
    id: "information-we-collect",
    number: "1",
    title: "Information We Collect",
    blocks: [
      "We may collect information directly from you, automatically through your use of the Platform, and from third parties in connection with operating Head-Hunters.com.",
      "The information collected depends on whether you use the Platform as a Company, Recruiter, candidate, visitor, or other user.",
      { sub: "Account and Identity Information" },
      "When you create or maintain an account, we may collect information such as:",
      {
        list: [
          "Name;",
          "Email address;",
          "Telephone number;",
          "Username and account credentials;",
          "Mailing or business address;",
          "Profile photograph;",
          "Professional title;",
          "Company or organization;",
          "Recruiter or Company profile information;",
          "Website and professional profile links;",
          "Account verification information; and",
          "Other information you voluntarily provide.",
        ],
      },
      { sub: "Company Information" },
      "Companies using Head-Hunters.com may provide information including:",
      {
        list: [
          "Company name;",
          "Company address and location;",
          "Company website;",
          "Contact information;",
          "Job openings;",
          "Job descriptions;",
          "Compensation ranges;",
          "Hiring requirements;",
          "Required or preferred qualifications;",
          "Recruiting fees;",
          "Hiring timelines;",
          "Candidate feedback;",
          "Interview information;",
          "Hiring decisions; and",
          "Other information relating to recruiting activities.",
        ],
      },
      "Some Company information may be publicly available or visible to Recruiters through the Platform.",
      { sub: "Recruiter Information" },
      "Recruiters may provide information including:",
      {
        list: [
          "Name and contact information;",
          "Professional experience;",
          "Recruiting specialties;",
          "Geographic markets;",
          "Industry expertise;",
          "Placement history;",
          "Candidate submissions;",
          "Professional profile information;",
          "Payment or payout information; and",
          "Other information relevant to providing recruiting services.",
        ],
      },
      "Certain Recruiter profile information may be visible to Companies or other authorized Platform users.",
    ],
  },
  {
    id: "candidate-information",
    number: "2",
    title: "Candidate Information",
    blocks: [
      "Because Head-Hunters.com is a recruiting marketplace, the Platform may process personal information relating to employment candidates.",
      "Candidate information may include:",
      {
        list: [
          "Name;",
          "Email address;",
          "Telephone number;",
          "City, state, or general location;",
          "Resume or curriculum vitae;",
          "Employment history;",
          "Education;",
          "Professional qualifications;",
          "Skills;",
          "Certifications and licenses;",
          "Compensation expectations;",
          "Employment preferences;",
          "Work authorization information;",
          "Professional profile links;",
          "Interview information;",
          "Candidate communications;",
          "Recruiter notes;",
          "Company feedback;",
          "Application or submission history; and",
          "Other information relevant to evaluating the candidate for employment.",
        ],
      },
      "Recruiters submitting candidate information are responsible for having an appropriate lawful basis, permission, authorization, or other legal right to provide such information to Head-Hunters.com and prospective Companies as required by applicable law.",
      "Candidate information provided through the Platform is intended to be used for legitimate recruiting, hiring, employment, Platform administration, fraud prevention, dispute resolution, and related purposes.",
      "Companies and Recruiters may not use candidate information obtained through Head-Hunters.com for unrelated marketing, resale, data brokerage, harassment, discrimination, or other unauthorized purposes.",
    ],
  },
  {
    id: "payment-information",
    number: "3",
    title: "Payment and Financial Information",
    blocks: [
      "Head-Hunters.com may collect or facilitate the collection of information necessary to process:",
      {
        list: [
          "Recruiting fees;",
          "Platform fees;",
          "Subscription payments;",
          "Placement payments;",
          "Recruiter payouts;",
          "Refunds or credits;",
          "Taxes;",
          "Payment disputes; and",
          "Other financial transactions.",
        ],
      },
      "Payment transactions may be processed by third-party payment processors.",
      "Where a third-party payment processor is used, payment card numbers, bank account information, and similar financial credentials may be collected and stored directly by that processor rather than Head-Hunters.com.",
      "We may receive transaction-related information such as payment status, transaction amounts, payment method type, billing information, payout status, transaction identifiers, and other information needed to administer payments and maintain financial records.",
    ],
  },
  {
    id: "collected-automatically",
    number: "4",
    title: "Information Collected Automatically",
    blocks: [
      "When you access or use Head-Hunters.com, we or our service providers may automatically collect certain technical and usage information, including:",
      {
        list: [
          "IP address;",
          "Browser type;",
          "Device type;",
          "Operating system;",
          "Device identifiers;",
          "Approximate location derived from an IP address;",
          "Pages viewed;",
          "Features used;",
          "Searches performed;",
          "Job postings viewed;",
          "Candidate submissions;",
          "Login activity;",
          "Referring pages;",
          "Date and time of access;",
          "Session information;",
          "Clickstream and interaction information; and",
          "Error and diagnostic information.",
        ],
      },
      "We may use cookies, pixels, software development kits, local storage, and similar technologies to collect some of this information.",
    ],
  },
  {
    id: "how-we-use",
    number: "5",
    title: "How We Use Information",
    blocks: [
      "Head-Hunters.com may use personal information to:",
      {
        list: [
          "Create and maintain user accounts;",
          "Authenticate users and protect account security;",
          "Operate the recruiting marketplace;",
          "Connect Companies with Recruiters;",
          "Facilitate candidate introductions;",
          "Allow Recruiters to submit candidates;",
          "Allow Companies to review candidates;",
          "Facilitate communications between Platform participants;",
          "Process payments and Recruiter payouts;",
          "Calculate and collect Platform and recruiting fees;",
          "Administer placement guarantees;",
          "Maintain records of candidate introductions;",
          "Determine candidate submission timing and history;",
          "Investigate candidate ownership disputes;",
          "Detect and investigate attempted fee circumvention;",
          "Prevent fraud and misuse of the Platform;",
          "Enforce our Terms of Service;",
          "Provide customer support;",
          "Improve Platform functionality;",
          "Analyze Platform usage;",
          "Diagnose technical problems;",
          "Develop new features and services;",
          "Communicate service announcements and account information;",
          "Send marketing communications where permitted by law;",
          "Comply with legal and regulatory obligations;",
          "Establish, exercise, or defend legal claims; and",
          "Protect Head-Hunters.com, its users, candidates, and others.",
        ],
      },
    ],
  },
  {
    id: "platform-records",
    number: "6",
    title: "Candidate Introduction and Platform Records",
    blocks: [
      "Head-Hunters.com may maintain records showing when a candidate was submitted, introduced, viewed, interviewed, or otherwise associated with a Company or recruiting opportunity.",
      "These records help operate the marketplace and may be used to:",
      {
        list: [
          "Determine which Recruiter submitted a candidate;",
          "Document candidate introductions;",
          "Determine whether a recruiting fee may be owed;",
          "Investigate duplicate candidate submissions;",
          "Investigate candidate ownership disputes;",
          "Enforce non-circumvention requirements;",
          "Investigate suspected candidate theft or fee avoidance; and",
          "Resolve Platform-related disputes.",
        ],
      },
      "We may retain relevant records after a job closes, candidate is hired, or user account is terminated when reasonably necessary for these purposes or otherwise permitted or required by law.",
    ],
  },
  {
    id: "how-we-disclose",
    number: "7",
    title: "How We Disclose Information",
    blocks: [
      "We may disclose personal information when reasonably necessary to operate Head-Hunters.com.",
      { sub: "Between Companies and Recruiters" },
      "Information may be disclosed between Companies and Recruiters to facilitate recruiting activities, candidate submissions, interviews, feedback, hiring decisions, and placements.",
      { sub: "Candidate Information Provided to Companies" },
      "Candidate information may be made available to Companies when a Recruiter submits or introduces a candidate for a position or as otherwise permitted through the Platform.",
      "Companies receiving candidate information are responsible for handling that information in accordance with applicable law and the Head-Hunters.com Terms of Service.",
      { sub: "Service Providers" },
      "We may disclose information to vendors and service providers that help us operate the Platform, including providers of:",
      {
        list: [
          "Cloud hosting;",
          "Data storage;",
          "Payment processing;",
          "Email and communications;",
          "Customer support;",
          "Cybersecurity;",
          "Fraud prevention;",
          "Analytics;",
          "Identity or account verification; and",
          "Other business and technology services.",
        ],
      },
      "These providers may process information on our behalf or under their own applicable privacy terms, depending on the service.",
    ],
  },
  {
    id: "legal-disclosures",
    number: "8",
    title: "Legal and Safety Disclosures",
    blocks: [
      "We may disclose information when we reasonably believe disclosure is necessary to:",
      {
        list: [
          "Comply with applicable law;",
          "Respond to a subpoena, court order, warrant, or other lawful request;",
          "Cooperate with governmental or regulatory authorities;",
          "Investigate fraud or unlawful activity;",
          "Enforce our Terms of Service or other agreements;",
          "Investigate fee circumvention or payment disputes;",
          "Establish or defend legal claims;",
          "Protect the security or integrity of Head-Hunters.com;",
          "Protect the rights, property, or safety of users, candidates, Head-Hunters.com, or others; or",
          "Prevent or investigate suspected misconduct.",
        ],
      },
    ],
  },
  {
    id: "business-transactions",
    number: "9",
    title: "Business Transactions",
    blocks: [
      "If Head-Hunters.com is involved in a merger, acquisition, financing, reorganization, bankruptcy, sale of assets, investment transaction, or similar corporate event, information may be disclosed or transferred as part of that transaction, subject to applicable law.",
      "Any successor entity may continue to process information in accordance with this Privacy Policy unless users are notified otherwise as required by law.",
    ],
  },
  {
    id: "sale-and-sharing",
    number: "10",
    title: "Sale and Sharing of Personal Information",
    blocks: [
      "Head-Hunters.com does not intend its ordinary disclosure of candidate information to Companies for recruiting and hiring purposes to constitute the sale of candidate information.",
      "We may use third-party analytics, advertising, or marketing technologies. Certain privacy laws may define some transfers involving advertising or tracking technologies as a “sale”, “sharing”, or “targeted advertising” even when money is not exchanged.",
      "Where applicable law provides rights regarding these activities, Head-Hunters.com will provide mechanisms required by that law.",
    ],
  },
  {
    id: "cookies",
    number: "11",
    title: "Cookies and Similar Technologies",
    blocks: [
      "Head-Hunters.com may use cookies and similar technologies to:",
      {
        list: [
          "Keep users signed in;",
          "Remember preferences;",
          "Maintain Platform security;",
          "Prevent fraud;",
          "Understand Platform usage;",
          "Measure performance;",
          "Diagnose technical issues;",
          "Improve functionality; and",
          "Support analytics, advertising, or marketing where applicable.",
        ],
      },
      "Users may be able to manage certain cookies through browser settings or privacy controls made available through the Platform.",
      "Blocking some cookies may affect Platform functionality.",
      "Where legally required, we will request appropriate consent before using non-essential cookies or similar technologies.",
    ],
  },
  {
    id: "data-security",
    number: "12",
    title: "Data Security",
    blocks: [
      "Head-Hunters.com uses reasonable administrative, technical, and organizational safeguards designed to protect personal information from unauthorized access, loss, misuse, alteration, or disclosure.",
      "However, no website, database, internet transmission, or electronic storage system can be guaranteed to be completely secure.",
      "Users are responsible for protecting their passwords and account credentials and should notify Head-Hunters.com promptly if they believe their account has been accessed without authorization.",
    ],
  },
  {
    id: "data-retention",
    number: "13",
    title: "Data Retention",
    blocks: [
      "We retain personal information for as long as reasonably necessary to:",
      {
        list: [
          "Provide the Platform;",
          "Maintain user accounts;",
          "Facilitate recruiting transactions;",
          "Document candidate introductions;",
          "Process and document payments;",
          "Administer placement guarantees;",
          "Resolve candidate ownership or payment disputes;",
          "Detect or prevent fraud and fee circumvention;",
          "Maintain business and financial records;",
          "Comply with legal obligations;",
          "Enforce agreements; and",
          "Establish, exercise, or defend legal claims.",
        ],
      },
      "Different categories of information may be retained for different periods.",
      "Account deletion does not necessarily require immediate deletion of every record. We may retain information where reasonably necessary or legally permitted, including transaction records, candidate-introduction records, security records, fraud-prevention records, and information associated with existing legal obligations or disputes.",
    ],
  },
  {
    id: "your-rights",
    number: "14",
    title: "Your Privacy Choices and Rights",
    blocks: [
      "Depending on where you reside and applicable law, you may have rights concerning your personal information.",
      "These may include the right to:",
      {
        list: [
          "Request access to personal information;",
          "Request correction of inaccurate information;",
          "Request deletion of certain information;",
          "Request information regarding how personal information is processed;",
          "Obtain a portable copy of certain information;",
          "Opt out of certain advertising or data-sharing practices;",
          "Withdraw consent where processing is based on consent; and",
          "Appeal certain decisions regarding a privacy request where required by law.",
        ],
      },
      "These rights are not absolute and may be subject to legal exceptions.",
      "For example, Head-Hunters.com may retain information despite a deletion request when retention is reasonably necessary to complete a transaction, comply with law, maintain financial records, prevent fraud, enforce agreements, document candidate introductions, protect legal rights, or resolve disputes.",
    ],
  },
  {
    id: "privacy-requests",
    number: "15",
    title: "Privacy Requests",
    blocks: [
      "To submit an applicable privacy request, contact:",
      { strong: "Head-Hunters.com" },
      "Privacy Email: **info@head-hunters.com**",
      "We may need to verify your identity before processing certain requests.",
      "Authorized agents may submit requests on behalf of individuals where permitted by applicable law and where appropriate authorization can be verified.",
      "Head-Hunters.com will not unlawfully discriminate against individuals for exercising applicable privacy rights.",
    ],
  },
  {
    id: "candidate-privacy-requests",
    number: "16",
    title: "Candidate Privacy Requests",
    blocks: [
      "Candidates whose information has been submitted through Head-Hunters.com may contact us regarding personal information maintained by the Platform.",
      "Depending on applicable law and circumstances, candidates may request access, correction, or deletion of certain personal information.",
      "A candidate's information may have also been independently obtained or retained by a Recruiter or Company. Head-Hunters.com does not necessarily control copies of candidate information independently maintained by those parties.",
      "Candidates may therefore need to contact the applicable Recruiter or Company regarding information controlled independently by that party.",
    ],
  },
  {
    id: "marketing",
    number: "17",
    title: "Marketing Communications",
    blocks: [
      "Users may receive marketing or promotional communications from Head-Hunters.com where permitted by applicable law.",
      "Users may opt out of promotional emails using the unsubscribe mechanism provided in those communications or other available account settings.",
      "Opting out of marketing communications does not prevent Head-Hunters.com from sending necessary transactional or service-related communications, including security alerts, payment notices, candidate activity, account information, legal notices, or changes affecting use of the Platform.",
    ],
  },
  {
    id: "childrens-privacy",
    number: "18",
    title: "Children's Privacy",
    blocks: [
      "Head-Hunters.com is a professional recruiting marketplace and is not intended for children under 18.",
      "We do not knowingly collect personal information from children through the Platform for purposes of creating recruiting marketplace accounts.",
      "If we learn that personal information from a child has been collected in violation of applicable law, we will take appropriate steps to address the information.",
    ],
  },
  {
    id: "international",
    number: "19",
    title: "International Users and Data Transfers",
    blocks: [
      "Head-Hunters.com may operate in the United States and may use service providers located in the United States or other countries.",
      "If you access the Platform from outside the United States, your information may be transferred to, processed in, or stored in countries whose privacy laws differ from those in your jurisdiction.",
      "Where required by applicable law, Head-Hunters.com will use appropriate mechanisms for international transfers of personal information.",
    ],
  },
  {
    id: "third-party-links",
    number: "20",
    title: "Third-Party Links",
    blocks: [
      "The Platform may contain links to websites, professional networking profiles, Company websites, or other third-party services.",
      "Head-Hunters.com is not responsible for the privacy practices of independent third parties.",
      "Users should review the privacy policies of third-party websites and services before providing personal information to them.",
    ],
  },
  {
    id: "user-responsibilities",
    number: "21",
    title: "Recruiter and Company Responsibilities for Personal Data",
    blocks: [
      "Companies and Recruiters may independently receive personal information through Head-Hunters.com.",
      "Each Company and Recruiter is responsible for complying with privacy and data protection laws applicable to its own collection, use, storage, disclosure, and retention of personal information.",
      "Head-Hunters.com does not authorize users to use information obtained through the Platform for unlawful purposes.",
      "A user's access to information through Head-Hunters.com does not grant ownership of that information or an unrestricted right to use it.",
    ],
  },
  {
    id: "accuracy",
    number: "22",
    title: "Accuracy of Information",
    blocks: [
      "Users are responsible for providing accurate information about themselves and keeping account information reasonably current.",
      "Head-Hunters.com may provide tools allowing users to update certain account information.",
      "We are not responsible for inaccurate information submitted by a Company, Recruiter, candidate, or other third party, although we may correct or remove information when appropriate.",
    ],
  },
  {
    id: "changes",
    number: "23",
    title: "Changes to This Privacy Policy",
    blocks: [
      {
        strong:
          "Head-Hunters.com reserves the right to modify or update this Privacy Policy from time to time.",
      },
      "When changes are made, we may update the “Last Updated” date at the top of this Policy and provide additional notice where required by applicable law.",
      "Your continued use of Head-Hunters.com following an updated Privacy Policy acknowledges the updated practices described in the Policy, subject to any consent requirements or other rights provided by applicable law.",
      "If a change requires affirmative consent under applicable law, Head-Hunters.com will seek that consent before applying the change as required.",
    ],
  },
  {
    id: "relationship-to-terms",
    number: "24",
    title: "Relationship to Terms of Service",
    blocks: [
      "Use of Head-Hunters.com is also governed by our **Terms of Service**.",
      "The Terms of Service contain important provisions regarding user responsibilities, recruiting fees, candidate introductions, payment obligations, non-circumvention, placement guarantees, limitations of liability, and other Platform requirements.",
      "This Privacy Policy describes our privacy practices and should be read together with the Terms of Service.",
    ],
  },
  {
    id: "contact",
    number: "25",
    title: "Contact Head-Hunters.com",
    blocks: [
      "Questions, concerns, or requests regarding this Privacy Policy or our privacy practices may be directed to:",
      { strong: "Head-Hunters.com" },
      "Support Email: **info@head-hunters.com**",
    ],
  },
];
